export const classEnum = [
  "strategicSword",
  "heavenquakerSpear",
  "namelessSword",
  "namelessSpear",
  "vernalUmbrella",
  "inkwellFan",
  "soulshadeUmbrella",
  "panaceaFan",
  "thundercryBlade",
  "stormreakerSpear",
  "infernalTwinblades",
  "mortalRopeDart",
  "everspringUmbrella",
  "unFetteredRopeDart",
] as const;
